version: "3.9"

services:
  log-assistant:
    build: .
    container_name: log_assistant
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
